# Test configuration with toggle-dependent fields
basics:
  kolla_base_distro: ubuntu
  kolla_install_type: source
  kolla_internal_vip_address: 192.168.1.100
  kolla_external_vip_address: 192.168.1.101
  kolla_internal_fqdn: internal.example.com
  kolla_external_fqdn: external.example.com
  network_interface: eth0
  neutron_external_interface: eth1
  
  # These toggles should enable dependent fields
  kolla_enable_tls_external: yes
  kolla_enable_tls_internal: yes

# Fields that should become visible when TLS toggles are enabled
  kolla_internal_fqdn_cert: /etc/xavs/certificates/internal_cert.pem
  kolla_external_fqdn_cert: /etc/xavs/certificates/external_cert.pem

storage:
  # This toggle should enable cinder-related fields
  enable_cinder: yes
  
  # These fields should be visible when cinder is enabled
  cinder_volume_group: cinder-volumes
  volume_driver: lvm
  cinder_backup_driver: swift

network:
  # Network-related toggles
  enable_neutron_provider_networks: yes
  enable_neutron_dvr: no

deploy_nodes:
  target_nodes: "node1,node2,node3"
  deploy_registry: localhost:4000
