# Test configuration with certificate file paths
basics:
  kolla_base_distro: ubuntu
  kolla_install_type: source
  kolla_internal_vip_address: 192.168.1.100
  kolla_external_vip_address: 192.168.1.101
  kolla_internal_fqdn: internal.example.com
  kolla_external_fqdn: external.example.com
  kolla_internal_fqdn_cert: /etc/xavs/certificates/internal_cert.pem
  kolla_external_fqdn_cert: /etc/xavs/certificates/external_cert.pem
  network_interface: eth0
  neutron_external_interface: eth1
  kolla_enable_tls_external: yes
  kolla_enable_tls_internal: yes

deploy_nodes:
  target_nodes: "node1,node2,node3"
  deploy_registry: localhost:4000

cinder:
  cinder_volume_group: cinder-volumes
  cinder_backup_driver: swift
